# Generated by Django 5.0.6 on 2024-09-24 03:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='defualtInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.IntegerField(choices=[(0, 'Шүүгч нар'), (1, 'Тамгын газар')], default=0)),
                ('info', ckeditor.fields.RichTextField()),
                ('images', models.ImageField(blank=True, upload_to='defaultInfo/')),
            ],
        ),
    ]
